---

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 127.0.0.1:8282:8080

volumes:
  data:
  keys:
